import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import {toast} from 'sonner';
import workerService from '../../services/worker.service'; // Adjust path if needed
import Loader from '../../components/common/Loader';

const loadRazorpayScript = () => {
  return new Promise((resolve) => {
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

export default function WorkerWallet() {
  const [balance, setBalance] = useState(0);
  const [loading, setLoading] = useState(true);
  const [isPaying, setIsPaying] = useState(false);

  const PAYWALL_LIMIT = -500;

 useEffect(() => {
    // 🚀 Changed this to getMyProfile so it perfectly matches the Dashboard!
    workerService.getMyProfile()
      .then((profile) => {
        // Grab the walletBalance from the profile (default to 0 if it doesn't exist)
        setBalance(profile.walletBalance || 0);
      })
      .catch(() => toast.error('Failed to load wallet data'))
      .finally(() => setLoading(false));
  }, []);

 const handlePayDues = async () => {
    setIsPaying(true);
    try {
      const res = await loadRazorpayScript();
      if (!res) {
        toast.error('Razorpay failed to load. Check your internet connection.');
        setIsPaying(false);
        return;
      }

      // 🚀 1. REMOVE THE MOCK DATA AND USE THE REAL API CALL
      const orderData = await workerService.createPaymentOrder(); 
      
      // Safety check just in case the backend fails to send an order ID
      if (!orderData || !orderData.id) {
        toast.error('Failed to generate a valid order from the server.');
        setIsPaying(false);
        return;
      }

      // 2. Open Razorpay with the REAL order ID
      const options = {
        key: 'rzp_test_TPWeDr1oQa6tX6', // I see your test key from the console logs!
        amount: orderData.amount,
        currency: orderData.currency,
        name: 'WorkMitra',
        description: 'Platform Dues Settlement',
        order_id: orderData.id, // <--- This is now a REAL ID generated by your backend!
        handler: async function (response) {
          try {
            await workerService.verifyPayment({
              razorpay_order_id: response.razorpay_order_id,
              razorpay_payment_id: response.razorpay_payment_id,
              razorpay_signature: response.razorpay_signature
            });
            
            toast.success('Payment successful! Your dues are cleared.');
            setBalance(0);
          } catch (err) {
            toast.error('Payment verification failed.');
          }
        },
        theme: { color: '#f97316' }
      };

      const paymentObject = new window.Razorpay(options);
      paymentObject.open();
      
    } catch (error) {
      console.error("Payment Error:", error);
      toast.error(error.response?.data?.message || 'Failed to initiate payment.');
    } finally {
      setIsPaying(false);
    }
  };

  if (loading) return <Loader text="Loading your wallet..." />;

  // Math for the visualizer
  const isLockedOut = balance <= PAYWALL_LIMIT;
  const owesMoney = balance < 0;
  // Calculate percentage (0 to 100) of how close they are to the -500 limit
  const limitPercentage = owesMoney ? Math.min((Math.abs(balance) / Math.abs(PAYWALL_LIMIT)) * 100, 100) : 0;

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pt-24 px-4 max-w-3xl mx-auto pb-12">
      
      <div className="mb-8">
        <h1 className="text-3xl font-black text-zinc-900 dark:text-white tracking-tight">My Wallet</h1>
        <p className="text-zinc-500 dark:text-zinc-400 font-medium mt-1">Manage your earnings and platform dues</p>
      </div>

      {/* Main Balance Card */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
        className="bg-zinc-900 dark:bg-white rounded-[2rem] p-8 text-white dark:text-zinc-900 shadow-2xl relative overflow-hidden mb-8"
      >
        <div className="absolute -right-20 -top-20 w-64 h-64 bg-orange-500/20 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10 flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <p className="text-sm font-bold uppercase tracking-widest opacity-80 mb-2">Current Balance</p>
            <div className="flex items-center gap-4">
              <h2 className="text-5xl md:text-6xl font-black tracking-tighter">
                {owesMoney ? '-' : ''}₹{Math.abs(balance).toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </h2>
            </div>
            <p className="mt-2 text-sm font-medium opacity-80">
              {owesMoney 
                ? "You collected cash from customers. This is the platform fee you owe us." 
                : "You have no pending dues! Keep up the great work."}
            </p>
          </div>

          {owesMoney && (
            <button 
              onClick={handlePayDues}
              disabled={isPaying}
              className="h-14 px-8 bg-orange-500 hover:bg-orange-600 text-white rounded-xl font-bold shadow-lg shadow-orange-500/20 hover:scale-[1.02] active:scale-[0.98] transition-all whitespace-nowrap disabled:opacity-70 flex items-center justify-center gap-2"
            >
              {isPaying ? (
                <span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
              )}
              {isPaying ? 'Processing...' : 'Pay Dues Now'}
            </button>
          )}
        </div>
      </motion.div>

      {/* Credit Limit Visualizer */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
        className={`border rounded-3xl p-6 md:p-8 mb-8 transition-colors ${
          isLockedOut 
            ? 'bg-red-50 dark:bg-red-500/5 border-red-200 dark:border-red-500/20' 
            : 'bg-white dark:bg-[#0a0a0a] border-zinc-200 dark:border-white/10'
        }`}
      >
        <div className="flex justify-between items-end mb-4">
          <div>
            <h3 className={`text-lg font-black ${isLockedOut ? 'text-red-600 dark:text-red-400' : 'text-zinc-900 dark:text-white'}`}>
              Credit Limit
            </h3>
            <p className={`text-sm font-medium ${isLockedOut ? 'text-red-600/80 dark:text-red-400/80' : 'text-zinc-500'}`}>
              Maximum allowed dues: ₹{Math.abs(PAYWALL_LIMIT)}
            </p>
          </div>
          <p className="text-sm font-bold text-zinc-900 dark:text-white">
            {limitPercentage.toFixed(0)}% Used
          </p>
        </div>

        {/* Progress Bar */}
        <div className="w-full h-4 bg-zinc-100 dark:bg-white/5 rounded-full overflow-hidden">
          <motion.div 
            initial={{ width: 0 }}
            animate={{ width: `${limitPercentage}%` }}
            transition={{ duration: 1, ease: "easeOut" }}
            className={`h-full rounded-full ${
              isLockedOut ? 'bg-red-500 shadow-[0_0_15px_rgba(239,68,68,0.5)]' 
              : limitPercentage > 75 ? 'bg-amber-500' 
              : 'bg-emerald-500'
            }`}
          />
        </div>

        {isLockedOut && (
          <div className="mt-6 flex items-start gap-3 p-4 bg-red-100 dark:bg-red-500/10 rounded-xl text-red-700 dark:text-red-400">
            <svg className="w-6 h-6 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
            <div>
              <p className="font-bold">Account Temporarily Locked</p>
              <p className="text-sm font-medium mt-0.5 opacity-90">You have reached the maximum credit limit. You cannot accept new job requests until your dues are cleared.</p>
            </div>
          </div>
        )}
      </motion.div>

      {/* How it works card */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
        className="bg-zinc-50 dark:bg-white/5 border border-zinc-200 dark:border-white/10 rounded-3xl p-6"
      >
        <h4 className="text-sm font-bold text-zinc-900 dark:text-white uppercase tracking-widest mb-4">How the Wallet Works</h4>
        <ul className="space-y-4">
          <li className="flex gap-3 text-sm font-medium text-zinc-600 dark:text-zinc-400">
            <span className="w-6 h-6 rounded-full bg-blue-100 dark:bg-blue-500/20 text-blue-600 dark:text-blue-400 flex items-center justify-center shrink-0 font-bold">1</span>
            When you complete a cash job, you keep 100% of the physical cash the customer hands you.
          </li>
          <li className="flex gap-3 text-sm font-medium text-zinc-600 dark:text-zinc-400">
            <span className="w-6 h-6 rounded-full bg-blue-100 dark:bg-blue-500/20 text-blue-600 dark:text-blue-400 flex items-center justify-center shrink-0 font-bold">2</span>
            WorkMitra's platform fee is automatically deducted from this digital wallet, resulting in a negative balance.
          </li>
          <li className="flex gap-3 text-sm font-medium text-zinc-600 dark:text-zinc-400">
            <span className="w-6 h-6 rounded-full bg-blue-100 dark:bg-blue-500/20 text-blue-600 dark:text-blue-400 flex items-center justify-center shrink-0 font-bold">3</span>
            Once your balance hits the limit (-₹500), you must pay the platform dues online to continue receiving jobs.
          </li>
        </ul>
      </motion.div>

    </motion.div>
  );
}