require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const User = require('./models/User');
const WorkerProfile = require('./models/WorkerProfile');
const Booking = require('./models/Booking');
const Review = require('./models/Review');
const Notification = require('./models/Notification');

// ─── Realistic Indian data ────────────────────────────────────────────────────

const WORKER_DATA = [
  // Electricians
  {
    name: 'Ramesh Kumar',
    email: 'ramesh.kumar@workmitra.com',
    phone: '9000000101',
    profession: 'Electrician',
    city: 'Delhi',
    state: 'Delhi',
    experienceYears: 8,
    rateAmount: 700,
    rateType: 'daily',
    skills: ['House Wiring', 'Panel Installation', 'Ceiling Fans', 'AC Fitting', 'Solar Panels'],
    languages: ['Hindi', 'English'],
    bio: 'Experienced electrician with 8 years in residential and commercial wiring. Specialized in smart home installations and solar panel setup. Available for both small repairs and large projects.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/14934022/pexels-photo-14934022.jpeg',
    ratingAvg: 4.8,
    ratingCount: 124,
    jobsCompleted: 312,
    earnings: 218400,
  },
  {
    name: 'Suresh Sharma',
    email: 'suresh.sharma@workmitra.com',
    phone: '9000000102',
    profession: 'Electrician',
    city: 'Mumbai',
    state: 'Maharashtra',
    experienceYears: 12,
    rateAmount: 900,
    rateType: 'daily',
    skills: ['Commercial Wiring', 'Generator Installation', 'CCTV', 'Home Automation', 'Inverter Setup'],
    languages: ['Hindi', 'Marathi', 'English'],
    bio: 'Master electrician with 12 years serving Mumbai\'s residential and commercial sector. Expert in home automation, CCTV installation, and generator setup. Fully licensed and insured.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/34054464/pexels-photo-34054464.jpeg',
    ratingAvg: 4.9,
    ratingCount: 203,
    jobsCompleted: 487,
    earnings: 438300,
  },
  {
    name: 'Manoj Verma',
    email: 'manoj.verma@workmitra.com',
    phone: '9000000103',
    profession: 'Electrician',
    city: 'Bangalore',
    state: 'Karnataka',
    experienceYears: 5,
    rateAmount: 150,
    rateType: 'hourly',
    skills: ['House Wiring', 'Switch Board Repair', 'Earthing', 'Short Circuit Fix'],
    languages: ['Hindi', 'Kannada', 'English'],
    bio: 'Young and skilled electrician based in Bangalore. Quick response time and affordable rates. Specializes in apartment electrical work and quick repairs.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/33118659/pexels-photo-33118659.jpeg',
    ratingAvg: 4.6,
    ratingCount: 67,
    jobsCompleted: 143,
    earnings: 85800,
  },
  // Plumbers
  {
    name: 'Dinesh Patel',
    email: 'dinesh.patel@workmitra.com',
    phone: '9000000104',
    profession: 'Plumber',
    city: 'Ahmedabad',
    state: 'Gujarat',
    experienceYears: 10,
    rateAmount: 600,
    rateType: 'daily',
    skills: ['Pipe Fitting', 'Bathroom Renovation', 'Water Tank', 'Drainage', 'Geyser Installation'],
    languages: ['Hindi', 'Gujarati'],
    bio: 'Expert plumber with a decade of experience in Ahmedabad. Specializes in complete bathroom renovations, pipe fitting, and water tank installations. Emergency services available 24/7.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/33388390/pexels-photo-33388390.jpeg',
    ratingAvg: 4.7,
    ratingCount: 98,
    jobsCompleted: 234,
    earnings: 140400,
  },
  {
    name: 'Raju Nair',
    email: 'raju.nair@workmitra.com',
    phone: '9000000105',
    profession: 'Plumber',
    city: 'Chennai',
    state: 'Tamil Nadu',
    experienceYears: 7,
    rateAmount: 120,
    rateType: 'hourly',
    skills: ['Leak Repair', 'Bathroom Fitting', 'Kitchen Plumbing', 'RO Installation', 'Water Heater'],
    languages: ['Tamil', 'English', 'Hindi'],
    bio: 'Certified plumber serving Chennai for 7 years. Known for quick response and clean work. Specialized in kitchen plumbing, bathroom fitting, and RO water purifier installation.',
    availability: 'busy',
    avatar: 'https://images.pexels.com/photos/34927382/pexels-photo-34927382.jpeg',
    ratingAvg: 4.5,
    ratingCount: 89,
    jobsCompleted: 198,
    earnings: 142560,
  },
  {
    name: 'Santosh Yadav',
    email: 'santosh.yadav@workmitra.com',
    phone: '9000000106',
    profession: 'Plumber',
    city: 'Hyderabad',
    state: 'Telangana',
    experienceYears: 15,
    rateAmount: 800,
    rateType: 'daily',
    skills: ['Industrial Plumbing', 'Pipeline Laying', 'Borewell', 'Sewage Treatment', 'Fire Hydrant'],
    languages: ['Telugu', 'Hindi', 'English'],
    bio: 'Senior plumber with 15 years specializing in industrial and large-scale plumbing projects in Hyderabad. Experienced in pipeline laying, sewage treatment, and fire hydrant systems.',
    availability: 'available',
    avatar: 'https://media.istockphoto.com/id/2205544490/photo/plumber-installing-water-filter-system-under-kitchen-sink.jpg?b=1&s=612x612&w=0&k=20&c=KUqIjGknj0LawhTEd1cRtgaOKPqN0zpOaJ9IMVwg_XU=',
    ratingAvg: 4.9,
    ratingCount: 312,
    jobsCompleted: 567,
    earnings: 453600,
  },
  // Carpenters
  {
    name: 'Govind Singh',
    email: 'govind.singh@workmitra.com',
    phone: '9000000107',
    profession: 'Carpenter',
    city: 'Jaipur',
    state: 'Rajasthan',
    experienceYears: 20,
    rateAmount: 850,
    rateType: 'daily',
    skills: ['Custom Furniture', 'Modular Kitchen', 'Wardrobes', 'False Ceiling', 'Wooden Flooring'],
    languages: ['Hindi', 'Rajasthani'],
    bio: 'Master carpenter with 20 years creating beautiful custom furniture and interiors. Specializes in traditional Rajasthani woodwork, modular kitchens, and luxury wardrobes. Has worked on 5-star hotel projects.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/33005110/pexels-photo-33005110.jpeg',
    ratingAvg: 5.0,
    ratingCount: 156,
    jobsCompleted: 289,
    earnings: 245650,
  },
  {
    name: 'Prakash Reddy',
    email: 'prakash.reddy@workmitra.com',
    phone: '9000000108',
    profession: 'Carpenter',
    city: 'Pune',
    state: 'Maharashtra',
    experienceYears: 9,
    rateAmount: 700,
    rateType: 'daily',
    skills: ['Door Frames', 'Window Fitting', 'Modular Furniture', 'Repair Work', 'Plywood Work'],
    languages: ['Marathi', 'Hindi', 'English'],
    bio: 'Skilled carpenter based in Pune with 9 years of experience. Expert in door and window fitting, modular furniture assembly, and repair work. Known for precision and timely delivery.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/18947381/pexels-photo-18947381.jpeg',
    ratingAvg: 4.6,
    ratingCount: 78,
    jobsCompleted: 167,
    earnings: 116900,
  },
  // Painters
  {
    name: 'Arun Mishra',
    email: 'arun.mishra@workmitra.com',
    phone: '9000000109',
    profession: 'Painter',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    experienceYears: 11,
    rateAmount: 500,
    rateType: 'daily',
    skills: ['Interior Painting', 'Exterior Painting', 'Texture Work', 'Wallpaper', 'Waterproofing'],
    languages: ['Hindi', 'Urdu'],
    bio: 'Professional painter with 11 years serving Lucknow. Expert in interior/exterior painting, texture work, and decorative finishes. Provides free color consultation. Uses premium paints only.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/5768187/pexels-photo-5768187.jpeg',
    ratingAvg: 4.7,
    ratingCount: 134,
    jobsCompleted: 298,
    earnings: 149000,
  },
  {
    name: 'Vijay Kumar',
    email: 'vijay.kumar@workmitra.com',
    phone: '9000000110',
    profession: 'Painter',
    city: 'Kolkata',
    state: 'West Bengal',
    experienceYears: 6,
    rateAmount: 400,
    rateType: 'daily',
    skills: ['Wall Painting', 'Graffiti Art', 'Logo Painting', 'Metal Painting', 'Rust Proofing'],
    languages: ['Bengali', 'Hindi', 'English'],
    bio: 'Creative painter with expertise in both traditional and artistic painting. Known for beautiful wall art, graffiti, and decorative finishes. Affordable rates and guaranteed quality work.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/31544574/pexels-photo-31544574.jpeg',
    ratingAvg: 4.8,
    ratingCount: 56,
    jobsCompleted: 112,
    earnings: 44800,
  },
  // AC Technicians
  {
    name: 'Deepak Chauhan',
    email: 'deepak.chauhan@workmitra.com',
    phone: '9000000111',
    profession: 'AC Technician',
    city: 'Delhi',
    state: 'Delhi',
    experienceYears: 9,
    rateAmount: 800,
    rateType: 'daily',
    skills: ['AC Installation', 'AC Servicing', 'Gas Refilling', 'AC Repair', 'Split AC', 'Window AC'],
    languages: ['Hindi', 'English'],
    bio: 'Certified AC technician with 9 years experience. Expert in all brands — LG, Samsung, Daikin, Voltas, Blue Star. Quick AC servicing, gas refilling, and installation. Same-day service available.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/33671149/pexels-photo-33671149.jpeg',
    ratingAvg: 4.9,
    ratingCount: 287,
    jobsCompleted: 634,
    earnings: 507200,
  },
  {
    name: 'Rajendra Pillai',
    email: 'rajendra.pillai@workmitra.com',
    phone: '9000000112',
    profession: 'AC Technician',
    city: 'Kochi',
    state: 'Kerala',
    experienceYears: 14,
    rateAmount: 180,
    rateType: 'hourly',
    skills: ['Cassette AC', 'Ductable AC', 'VRF Systems', 'Chiller Plant', 'AMC Services'],
    languages: ['Malayalam', 'English', 'Hindi'],
    bio: 'Senior AC technician specializing in commercial HVAC systems. 14 years experience with VRF systems, chiller plants, and ductable ACs. Authorized service partner for multiple brands.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/5463575/pexels-photo-5463575.jpeg',
    ratingAvg: 4.8,
    ratingCount: 198,
    jobsCompleted: 423,
    earnings: 456840,
  },
  // Masons
  {
    name: 'Bharat Singh',
    email: 'bharat.singh@workmitra.com',
    phone: '9000000113',
    profession: 'Mason',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    experienceYears: 18,
    rateAmount: 600,
    rateType: 'daily',
    skills: ['Brickwork', 'Plastering', 'Tiling', 'RCC Work', 'Waterproofing', 'Flooring'],
    languages: ['Hindi'],
    bio: 'Expert mason with 18 years in construction. Skilled in brickwork, plastering, tiling, and RCC work. Has worked on residential buildings, commercial complexes, and government projects.',
    availability: 'available',
    avatar: 'https://media.istockphoto.com/id/610442626/photo/master-mason.jpg?b=1&s=612x612&w=0&k=20&c=ZkCWrG9Qz_fiF9iIloWatHa_Tu6BOZ_10OiDpVS_-rw=',
    ratingAvg: 4.7,
    ratingCount: 89,
    jobsCompleted: 178,
    earnings: 106800,
  },
  {
    name: 'Ganesh Patil',
    email: 'ganesh.patil@workmitra.com',
    phone: '9000000114',
    profession: 'Mason',
    city: 'Nashik',
    state: 'Maharashtra',
    experienceYears: 13,
    rateAmount: 650,
    rateType: 'daily',
    skills: ['Stone Masonry', 'Marble Fitting', 'Granite Work', 'Swimming Pool', 'Bathroom Tiling'],
    languages: ['Marathi', 'Hindi'],
    bio: 'Specialized mason in stone masonry, marble fitting, and premium flooring. 13 years of crafting luxury spaces in Nashik and Pune. Expert in Italian marble, granite, and natural stone work.',
    availability: 'busy',
    avatar: 'https://images.pexels.com/photos/9172008/pexels-photo-9172008.jpeg',
    ratingAvg: 4.9,
    ratingCount: 112,
    jobsCompleted: 234,
    earnings: 152100,
  },
  // Welders
  {
    name: 'Harish Tiwari',
    email: 'harish.tiwari@workmitra.com',
    phone: '9000000115',
    profession: 'Welder',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    experienceYears: 16,
    rateAmount: 700,
    rateType: 'daily',
    skills: ['Arc Welding', 'MIG Welding', 'TIG Welding', 'Gate Fabrication', 'Steel Structures'],
    languages: ['Hindi'],
    bio: 'Experienced welder with 16 years in industrial and structural welding. Expert in arc, MIG, and TIG welding. Fabricates gates, grilles, steel structures, and custom metalwork.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/2880871/pexels-photo-2880871.jpeg',
    ratingAvg: 4.6,
    ratingCount: 67,
    jobsCompleted: 145,
    earnings: 101500,
  },
  {
    name: 'Mukesh Rawat',
    email: 'mukesh.rawat@workmitra.com',
    phone: '9000000116',
    profession: 'Welder',
    city: 'Surat',
    state: 'Gujarat',
    experienceYears: 8,
    rateAmount: 130,
    rateType: 'hourly',
    skills: ['Stainless Steel', 'Aluminium Welding', 'Railing Fabrication', 'Shed Construction', 'Repair Work'],
    languages: ['Hindi', 'Gujarati'],
    bio: 'Skilled welder specializing in stainless steel and aluminium work. Creates beautiful railings, staircases, sheds, and custom metalwork. 8 years serving Surat\'s diamond and textile industry.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/29224590/pexels-photo-29224590.jpeg',
    ratingAvg: 4.7,
    ratingCount: 89,
    jobsCompleted: 198,
    earnings: 154440,
  },
  // Construction
  {
    name: 'Shyam Babu',
    email: 'shyam.babu@workmitra.com',
    phone: '9000000117',
    profession: 'Construction Worker',
    city: 'Noida',
    state: 'Uttar Pradesh',
    experienceYears: 22,
    rateAmount: 550,
    rateType: 'daily',
    skills: ['Site Supervision', 'Civil Work', 'Foundation', 'Concrete Mixing', 'Project Management'],
    languages: ['Hindi', 'Bhojpuri'],
    bio: 'Experienced construction supervisor with 22 years on major projects across NCR. Expert in site management, foundation work, and quality control. Has supervised 50+ buildings.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/11293626/pexels-photo-11293626.jpeg',
    ratingAvg: 4.8,
    ratingCount: 45,
    jobsCompleted: 58,
    earnings: 31900,
  },
  {
    name: 'Anand Krishnan',
    email: 'anand.krishnan@workmitra.com',
    phone: '9000000118',
    profession: 'Construction Worker',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    experienceYears: 10,
    rateAmount: 500,
    rateType: 'daily',
    skills: ['Shuttering', 'Bar Bending', 'Concrete Work', 'Waterproofing', 'Demolition'],
    languages: ['Tamil', 'English'],
    bio: 'Skilled construction worker specializing in shuttering, bar bending, and concrete work. 10 years building homes and factories in Tamil Nadu. Reliable, hardworking, and safety-conscious.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/36601725/pexels-photo-36601725.jpeg',
    ratingAvg: 4.5,
    ratingCount: 34,
    jobsCompleted: 89,
    earnings: 44500,
  },
  // More
  {
    name: 'Karan Mehta',
    email: 'karan.mehta@workmitra.com',
    phone: '9000000119',
    profession: 'Electrician',
    city: 'Chandigarh',
    state: 'Punjab',
    experienceYears: 4,
    rateAmount: 120,
    rateType: 'hourly',
    skills: ['LED Lighting', 'Switchboard', 'Inverter', 'Fan Installation', 'Wiring'],
    languages: ['Hindi', 'Punjabi', 'English'],
    bio: 'Young and energetic electrician in Chandigarh. Specializes in LED lighting solutions and smart home basics. Fast, clean work with competitive rates. Available on weekends too.',
    availability: 'available',
    avatar: 'https://media.istockphoto.com/id/1369703493/photo/happy-smiling-electrician-with-crossed-arms-and-safety-precautions-standing-by-looking-at.jpg?b=1&s=612x612&w=0&k=20&c=pB1yTbvMmRk9tT5rvs4BRhmPp4MtXCrcEH7rCXW3IKk=',
    ratingAvg: 4.4,
    ratingCount: 28,
    jobsCompleted: 67,
    earnings: 48240,
  },
  {
    name: 'Sanjay Gupta',
    email: 'sanjay.gupta@workmitra.com',
    phone: '9000000120',
    profession: 'Plumber',
    city: 'Agra',
    state: 'Uttar Pradesh',
    experienceYears: 8,
    rateAmount: 500,
    rateType: 'daily',
    skills: ['Overhead Tank', 'Submersible Pump', 'Pipe Repair', 'Tap Fitting', 'Drainage'],
    languages: ['Hindi'],
    bio: 'Reliable plumber serving Agra for 8 years. Expert in overhead water tanks, submersible pump installation, and pipeline repair. Quick response for emergency leakages.',
    availability: 'available',
    avatar: 'https://media.istockphoto.com/id/1205228815/photo/male-plumber-working-to-fix-leaking-sink-in-home-bathroom.jpg?b=1&s=612x612&w=0&k=20&c=apvWPotFrWiLWhQLoU1NrYyPCWrZ9f3z6N31dsyRv8k=',
    ratingAvg: 4.6,
    ratingCount: 72,
    jobsCompleted: 156,
    earnings: 78000,
  },
  {
    name: 'Rohit Sharma',
    email: 'rohit.sharma@workmitra.com',
    phone: '9000000121',
    profession: 'Painter',
    city: 'Indore',
    state: 'Madhya Pradesh',
    experienceYears: 7,
    rateAmount: 450,
    rateType: 'daily',
    skills: ['Asian Paints', 'Berger Paints', 'Enamel Paint', 'Wood Polish', 'Wall Putty'],
    languages: ['Hindi'],
    bio: 'Professional painter in Indore with 7 years experience. Certified applicator for Asian Paints and Berger. Provides complete painting solutions from wall putty to final coat.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/34975633/pexels-photo-34975633.jpeg',
    ratingAvg: 4.7,
    ratingCount: 93,
    jobsCompleted: 187,
    earnings: 84150,
  },
  {
    name: 'Amit Joshi',
    email: 'amit.joshi@workmitra.com',
    phone: '9000000122',
    profession: 'Carpenter',
    city: 'Dehradun',
    state: 'Uttarakhand',
    experienceYears: 14,
    rateAmount: 750,
    rateType: 'daily',
    skills: ['Teak Wood', 'Sheesham Wood', 'Antique Restoration', 'Custom Cabinets', 'Staircase'],
    languages: ['Hindi', 'English'],
    bio: 'Master carpenter specializing in premium teak and sheesham woodwork. 14 years crafting custom furniture and restoring antique pieces. Known for intricate detailing and heirloom-quality work.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/4491916/pexels-photo-4491916.jpeg',
    ratingAvg: 4.9,
    ratingCount: 67,
    jobsCompleted: 123,
    earnings: 92250,
  },
  {
    name: 'Nikhil Pandey',
    email: 'nikhil.pandey@workmitra.com',
    phone: '9000000123',
    profession: 'AC Technician',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    experienceYears: 6,
    rateAmount: 600,
    rateType: 'daily',
    skills: ['AC Installation', 'PCB Repair', 'Compressor Replacement', 'Gas Charging', 'Cleaning'],
    languages: ['Hindi', 'Bhojpuri'],
    bio: 'AC specialist in Varanasi with 6 years experience. Expert in PCB repair, compressor replacement, and gas charging for all AC brands. Quick diagnosis and long-lasting repairs.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/5463576/pexels-photo-5463576.jpeg',
    ratingAvg: 4.5,
    ratingCount: 54,
    jobsCompleted: 112,
    earnings: 67200,
  },
  {
    name: 'Pradeep Nath',
    email: 'pradeep.nath@workmitra.com',
    phone: '9000000124',
    profession: 'Mason',
    city: 'Patna',
    state: 'Bihar',
    experienceYears: 25,
    rateAmount: 550,
    rateType: 'daily',
    skills: ['Traditional Masonry', 'Load Bearing Walls', 'Arch Construction', 'Heritage Work', 'Crack Repair'],
    languages: ['Hindi', 'Maithili', 'Bhojpuri'],
    bio: 'Senior mason with 25 years of experience. One of Patna\'s most trusted names in construction. Expert in traditional masonry and heritage building repair. Has worked on government restoration projects.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/12924578/pexels-photo-12924578.jpeg',
    ratingAvg: 4.8,
    ratingCount: 78,
    jobsCompleted: 189,
    earnings: 103950,
  },
  {
    name: 'Manoj Verma',
    email: 'manoj.verma@workmitra.com',
    phone: '9000000103',
    profession: 'Electrician',
    city: 'Bangalore',
    state: 'Karnataka',
    experienceYears: 5,
    rateAmount: 150,
    rateType: 'hourly',
    skills: ['House Wiring', 'Switch Board Repair', 'Earthing', 'Short Circuit Fix'],
    languages: ['Hindi', 'Kannada', 'English'],
    bio: 'Young and skilled electrician based in Bangalore. Quick response time and affordable rates. Specializes in apartment electrical work and quick repairs.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/34969202/pexels-photo-34969202.jpeg',
    ratingAvg: 4.6,
    ratingCount: 67,
    jobsCompleted: 143,
    earnings: 85800,
  },

  // Plumbers
  {
    name: 'Dinesh Patel',
    email: 'dinesh.patel@workmitra.com',
    phone: '9000000104',
    profession: 'Plumber',
    city: 'Ahmedabad',
    state: 'Gujarat',
    experienceYears: 10,
    rateAmount: 600,
    rateType: 'daily',
    skills: ['Pipe Fitting', 'Bathroom Renovation', 'Water Tank', 'Drainage', 'Geyser Installation'],
    languages: ['Hindi', 'Gujarati'],
    bio: 'Expert plumber with a decade of experience in Ahmedabad. Specializes in complete bathroom renovations, pipe fitting, and water tank installations. Emergency services available 24/7.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/12944825/pexels-photo-12944825.jpeg',
    ratingAvg: 4.7,
    ratingCount: 98,
    jobsCompleted: 234,
    earnings: 140400,
  },
  {
    name: 'Raju Nair',
    email: 'raju.nair@workmitra.com',
    phone: '9000000105',
    profession: 'Plumber',
    city: 'Chennai',
    state: 'Tamil Nadu',
    experienceYears: 7,
    rateAmount: 120,
    rateType: 'hourly',
    skills: ['Leak Repair', 'Bathroom Fitting', 'Kitchen Plumbing', 'RO Installation', 'Water Heater'],
    languages: ['Tamil', 'English', 'Hindi'],
    bio: 'Certified plumber serving Chennai for 7 years. Known for quick response and clean work. Specialized in kitchen plumbing, bathroom fitting, and RO water purifier installation.',
    availability: 'busy',
    avatar: 'https://images.pexels.com/photos/27354189/pexels-photo-27354189.jpeg',
    ratingAvg: 4.5,
    ratingCount: 89,
    jobsCompleted: 198,
    earnings: 142560,
  },
  {
    name: 'Santosh Yadav',
    email: 'santosh.yadav@workmitra.com',
    phone: '9000000106',
    profession: 'Plumber',
    city: 'Hyderabad',
    state: 'Telangana',
    experienceYears: 15,
    rateAmount: 800,
    rateType: 'daily',
    skills: ['Industrial Plumbing', 'Pipeline Laying', 'Borewell', 'Sewage Treatment', 'Fire Hydrant'],
    languages: ['Telugu', 'Hindi', 'English'],
    bio: 'Senior plumber with 15 years specializing in industrial and large-scale plumbing projects in Hyderabad. Experienced in pipeline laying, sewage treatment, and fire hydrant systems.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/32391500/pexels-photo-32391500.jpeg',
    ratingAvg: 4.9,
    ratingCount: 312,
    jobsCompleted: 567,
    earnings: 453600,
  },

  // Carpenters
  {
    name: 'Govind Singh',
    email: 'govind.singh@workmitra.com',
    phone: '9000000107',
    profession: 'Carpenter',
    city: 'Jaipur',
    state: 'Rajasthan',
    experienceYears: 20,
    rateAmount: 850,
    rateType: 'daily',
    skills: ['Custom Furniture', 'Modular Kitchen', 'Wardrobes', 'False Ceiling', 'Wooden Flooring'],
    languages: ['Hindi', 'Rajasthani'],
    bio: 'Master carpenter with 20 years creating beautiful custom furniture and interiors. Specializes in traditional Rajasthani woodwork, modular kitchens, and luxury wardrobes. Has worked on 5-star hotel projects.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/34434408/pexels-photo-34434408.jpeg',
    ratingAvg: 5.0,
    ratingCount: 156,
    jobsCompleted: 289,
    earnings: 245650,
  },
  {
    name: 'Prakash Reddy',
    email: 'prakash.reddy@workmitra.com',
    phone: '9000000108',
    profession: 'Carpenter',
    city: 'Pune',
    state: 'Maharashtra',
    experienceYears: 9,
    rateAmount: 700,
    rateType: 'daily',
    skills: ['Door Frames', 'Window Fitting', 'Modular Furniture', 'Repair Work', 'Plywood Work'],
    languages: ['Marathi', 'Hindi', 'English'],
    bio: 'Skilled carpenter based in Pune with 9 years of experience. Expert in door and window fitting, modular furniture assembly, and repair work. Known for precision and timely delivery.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/5711881/pexels-photo-5711881.jpeg',
    ratingAvg: 4.6,
    ratingCount: 78,
    jobsCompleted: 167,
    earnings: 116900,
  },

  // Painters
  {
    name: 'Arun Mishra',
    email: 'arun.mishra@workmitra.com',
    phone: '9000000109',
    profession: 'Painter',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    experienceYears: 11,
    rateAmount: 500,
    rateType: 'daily',
    skills: ['Interior Painting', 'Exterior Painting', 'Texture Work', 'Wallpaper', 'Waterproofing'],
    languages: ['Hindi', 'Urdu'],
    bio: 'Professional painter with 11 years serving Lucknow. Expert in interior/exterior painting, texture work, and decorative finishes. Provides free color consultation. Uses premium paints only.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/16747104/pexels-photo-16747104.jpeg',
    ratingAvg: 4.7,
    ratingCount: 134,
    jobsCompleted: 298,
    earnings: 149000,
  },
  {
    name: 'Vijay Kumar',
    email: 'vijay.kumar@workmitra.com',
    phone: '9000000110',
    profession: 'Painter',
    city: 'Kolkata',
    state: 'West Bengal',
    experienceYears: 6,
    rateAmount: 400,
    rateType: 'daily',
    skills: ['Wall Painting', 'Graffiti Art', 'Logo Painting', 'Metal Painting', 'Rust Proofing'],
    languages: ['Bengali', 'Hindi', 'English'],
    bio: 'Creative painter with expertise in both traditional and artistic painting. Known for beautiful wall art, graffiti, and decorative finishes. Affordable rates and guaranteed quality work.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/13718311/pexels-photo-13718311.jpeg',
    ratingAvg: 4.8,
    ratingCount: 56,
    jobsCompleted: 112,
    earnings: 44800,
  },

  // AC Technicians
  {
    name: 'Deepak Chauhan',
    email: 'deepak.chauhan@workmitra.com',
    phone: '9000000111',
    profession: 'AC Technician',
    city: 'Delhi',
    state: 'Delhi',
    experienceYears: 9,
    rateAmount: 800,
    rateType: 'daily',
    skills: ['AC Installation', 'AC Servicing', 'Gas Refilling', 'AC Repair', 'Split AC', 'Window AC'],
    languages: ['Hindi', 'English'],
    bio: 'Certified AC technician with 9 years experience. Expert in all brands — LG, Samsung, Daikin, Voltas, Blue Star. Quick AC servicing, gas refilling, and installation. Same-day service available.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/10958586/pexels-photo-10958586.jpeg',
    ratingAvg: 4.9,
    ratingCount: 287,
    jobsCompleted: 634,
    earnings: 507200,
  },
  {
    name: 'Rajendra Pillai',
    email: 'rajendra.pillai@workmitra.com',
    phone: '9000000112',
    profession: 'AC Technician',
    city: 'Kochi',
    state: 'Kerala',
    experienceYears: 14,
    rateAmount: 180,
    rateType: 'hourly',
    skills: ['Cassette AC', 'Ductable AC', 'VRF Systems', 'Chiller Plant', 'AMC Services'],
    languages: ['Malayalam', 'English', 'Hindi'],
    bio: 'Senior AC technician specializing in commercial HVAC systems. 14 years experience with VRF systems, chiller plants, and ductable ACs. Authorized service partner for multiple brands.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/7347538/pexels-photo-7347538.jpeg',
    ratingAvg: 4.8,
    ratingCount: 198,
    jobsCompleted: 423,
    earnings: 456840,
  },

  // Masons
  {
    name: 'Bharat Singh',
    email: 'bharat.singh@workmitra.com',
    phone: '9000000113',
    profession: 'Mason',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    experienceYears: 18,
    rateAmount: 600,
    rateType: 'daily',
    skills: ['Brickwork', 'Plastering', 'Tiling', 'RCC Work', 'Waterproofing', 'Flooring'],
    languages: ['Hindi'],
    bio: 'Expert mason with 18 years in construction. Skilled in brickwork, plastering, tiling, and RCC work. Has worked on residential buildings, commercial complexes, and government projects. Leads a team of 5 workers.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/38207699/pexels-photo-38207699.jpeg',
    ratingAvg: 4.7,
    ratingCount: 89,
    jobsCompleted: 178,
    earnings: 106800,
  },
  {
    name: 'Ganesh Patil',
    email: 'ganesh.patil@workmitra.com',
    phone: '9000000114',
    profession: 'Mason',
    city: 'Nashik',
    state: 'Maharashtra',
    experienceYears: 13,
    rateAmount: 650,
    rateType: 'daily',
    skills: ['Stone Masonry', 'Marble Fitting', 'Granite Work', 'Swimming Pool', 'Bathroom Tiling'],
    languages: ['Marathi', 'Hindi'],
    bio: 'Specialized mason in stone masonry, marble fitting, and premium flooring. 13 years of crafting luxury spaces in Nashik and Pune. Expert in Italian marble, granite, and natural stone work.',
    availability: 'busy',
    avatar: 'https://images.pexels.com/photos/14225905/pexels-photo-14225905.jpeg',
    ratingAvg: 4.9,
    ratingCount: 112,
    jobsCompleted: 234,
    earnings: 152100,
  },

  // Welders
  {
    name: 'Harish Tiwari',
    email: 'harish.tiwari@workmitra.com',
    phone: '9000000115',
    profession: 'Welder',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    experienceYears: 16,
    rateAmount: 700,
    rateType: 'daily',
    skills: ['Arc Welding', 'MIG Welding', 'TIG Welding', 'Gate Fabrication', 'Steel Structures'],
    languages: ['Hindi'],
    bio: 'Experienced welder with 16 years in industrial and structural welding. Expert in arc, MIG, and TIG welding. Fabricates gates, grilles, steel structures, and custom metalwork. Available for site work.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/37582043/pexels-photo-37582043.jpeg',
    ratingAvg: 4.6,
    ratingCount: 67,
    jobsCompleted: 145,
    earnings: 101500,
  },
  {
    name: 'Mukesh Rawat',
    email: 'mukesh.rawat@workmitra.com',
    phone: '9000000116',
    profession: 'Welder',
    city: 'Surat',
    state: 'Gujarat',
    experienceYears: 8,
    rateAmount: 130,
    rateType: 'hourly',
    skills: ['Stainless Steel', 'Aluminium Welding', 'Railing Fabrication', 'Shed Construction', 'Repair Work'],
    languages: ['Hindi', 'Gujarati'],
    bio: 'Skilled welder specializing in stainless steel and aluminium work. Creates beautiful railings, staircases, sheds, and custom metalwork. 8 years serving Surat\'s diamond and textile industry.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/37553012/pexels-photo-37553012.jpeg',
    ratingAvg: 4.7,
    ratingCount: 89,
    jobsCompleted: 198,
    earnings: 154440,
  },

  // Construction Workers / Supervisors
  {
    name: 'Shyam Babu',
    email: 'shyam.babu@workmitra.com',
    phone: '9000000117',
    profession: 'Construction Worker',
    city: 'Noida',
    state: 'Uttar Pradesh',
    experienceYears: 22,
    rateAmount: 550,
    rateType: 'daily',
    skills: ['Site Supervision', 'Civil Work', 'Foundation', 'Concrete Mixing', 'Project Management'],
    languages: ['Hindi', 'Bhojpuri'],
    bio: 'Experienced construction supervisor with 22 years on major projects across NCR. Expert in site management, foundation work, and quality control. Has supervised 50+ residential and commercial buildings.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/14796899/pexels-photo-14796899.jpeg',
    ratingAvg: 4.8,
    ratingCount: 45,
    jobsCompleted: 58,
    earnings: 31900,
  },
  {
    name: 'Anand Krishnan',
    email: 'anand.krishnan@workmitra.com',
    phone: '9000000118',
    profession: 'Construction Worker',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    experienceYears: 10,
    rateAmount: 500,
    rateType: 'daily',
    skills: ['Shuttering', 'Bar Bending', 'Concrete Work', 'Waterproofing', 'Demolition'],
    languages: ['Tamil', 'English'],
    bio: 'Skilled construction worker specializing in shuttering, bar bending, and concrete work. 10 years building homes and factories in Tamil Nadu. Reliable, hardworking, and safety-conscious.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/37556467/pexels-photo-37556467.jpeg',
    ratingAvg: 4.5,
    ratingCount: 34,
    jobsCompleted: 89,
    earnings: 44500,
  },

  // More variety
  {
    name: 'Karan Mehta',
    email: 'karan.mehta@workmitra.com',
    phone: '9000000119',
    profession: 'Electrician',
    city: 'Chandigarh',
    state: 'Punjab',
    experienceYears: 4,
    rateAmount: 120,
    rateType: 'hourly',
    skills: ['LED Lighting', 'Switchboard', 'Inverter', 'Fan Installation', 'Wiring'],
    languages: ['Hindi', 'Punjabi', 'English'],
    bio: 'Young and energetic electrician in Chandigarh. Specializes in LED lighting solutions and smart home basics. Fast, clean work with competitive rates. Available on weekends too.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/36892097/pexels-photo-36892097.jpeg',
    ratingAvg: 4.4,
    ratingCount: 28,
    jobsCompleted: 67,
    earnings: 48240,
  },
  {
    name: 'Sanjay Gupta',
    email: 'sanjay.gupta@workmitra.com',
    phone: '9000000120',
    profession: 'Plumber',
    city: 'Agra',
    state: 'Uttar Pradesh',
    experienceYears: 8,
    rateAmount: 500,
    rateType: 'daily',
    skills: ['Overhead Tank', 'Submersible Pump', 'Pipe Repair', 'Tap Fitting', 'Drainage'],
    languages: ['Hindi'],
    bio: 'Reliable plumber serving Agra for 8 years. Expert in overhead water tanks, submersible pump installation, and pipeline repair. Quick response for emergency leakages.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/7013085/pexels-photo-7013085.jpeg',
    ratingAvg: 4.6,
    ratingCount: 72,
    jobsCompleted: 156,
    earnings: 78000,
  },
  {
    name: 'Rohit Sharma',
    email: 'rohit.sharma@workmitra.com',
    phone: '9000000121',
    profession: 'Painter',
    city: 'Indore',
    state: 'Madhya Pradesh',
    experienceYears: 7,
    rateAmount: 450,
    rateType: 'daily',
    skills: ['Asian Paints', 'Berger Paints', 'Enamel Paint', 'Wood Polish', 'Wall Putty'],
    languages: ['Hindi'],
    bio: 'Professional painter in Indore with 7 years experience. Certified applicator for Asian Paints and Berger. Provides complete painting solutions from wall putty to final coat. Clean, efficient work guaranteed.',
    availability: 'available',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    ratingAvg: 4.7,
    ratingCount: 93,
    jobsCompleted: 187,
    earnings: 84150,
  },
  {
    name: 'Amit Joshi',
    email: 'amit.joshi@workmitra.com',
    phone: '9000000122',
    profession: 'Carpenter',
    city: 'Dehradun',
    state: 'Uttarakhand',
    experienceYears: 14,
    rateAmount: 750,
    rateType: 'daily',
    skills: ['Teak Wood', 'Sheesham Wood', 'Antique Restoration', 'Custom Cabinets', 'Staircase'],
    languages: ['Hindi', 'English'],
    bio: 'Master carpenter specializing in premium teak and sheesham woodwork. 14 years crafting custom furniture and restoring antique pieces. Known for intricate detailing and heirloom-quality work.',
    availability: 'available',
    avatar: 'https://media.istockphoto.com/id/1457344216/photo/confident-painter-standing-with-crossed-arms-by-holding-paint-brush-by-looking-camera-concept.jpg?b=1&s=612x612&w=0&k=20&c=W3nJbyGGBuLqtGTCjalkft0xEl-MPFX5WIlMPW9JXCA=',
    ratingAvg: 4.9,
    ratingCount: 67,
    jobsCompleted: 123,
    earnings: 92250,
  },
  {
    name: 'Nikhil Pandey',
    email: 'nikhil.pandey@workmitra.com',
    phone: '9000000123',
    profession: 'AC Technician',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    experienceYears: 6,
    rateAmount: 600,
    rateType: 'daily',
    skills: ['AC Installation', 'PCB Repair', 'Compressor Replacement', 'Gas Charging', 'Cleaning'],
    languages: ['Hindi', 'Bhojpuri'],
    bio: 'AC specialist in Varanasi with 6 years experience. Expert in PCB repair, compressor replacement, and gas charging for all AC brands. Quick diagnosis and long-lasting repairs. Home visits available.',
    availability: 'available',
    avatar: 'https://media.istockphoto.com/id/1324165671/photo/indian-man-setting-up-air-conditioner.jpg?b=1&s=612x612&w=0&k=20&c=E2zCMiNn_ldeIO7a4C1Je2bPs5psMBRUOfmskGVSP14=',
    ratingAvg: 4.5,
    ratingCount: 54,
    jobsCompleted: 112,
    earnings: 67200,
  },
  {
    name: 'Pradeep Nath',
    email: 'pradeep.nath@workmitra.com',
    phone: '9000000124',
    profession: 'Mason',
    city: 'Patna',
    state: 'Bihar',
    experienceYears: 25,
    rateAmount: 550,
    rateType: 'daily',
    skills: ['Traditional Masonry', 'Load Bearing Walls', 'Arch Construction', 'Heritage Work', 'Crack Repair'],
    languages: ['Hindi', 'Maithili', 'Bhojpuri'],
    bio: 'Senior mason with 25 years of experience. One of Patna\'s most trusted names in construction. Expert in traditional masonry, load-bearing walls, and heritage building repair. Has worked on government restoration projects.',
    availability: 'available',
    avatar: 'https://images.pexels.com/photos/9491951/pexels-photo-9491951.jpeg',
    ratingAvg: 4.8,
    ratingCount: 78,
    jobsCompleted: 189,
    earnings: 103950,
  },
];

const uniqueWorkers = [
  ...new Map(WORKER_DATA.map(worker => [worker.email, worker])).values()
];

const CUSTOMER_DATA = [
  { name: 'Priya Sharma', email: 'priya.sharma@gmail.com', phone: '9000000201', city: 'Delhi' },
  { name: 'Arjun Mehta', email: 'arjun.mehta@gmail.com', phone: '9000000202', city: 'Mumbai' },
  { name: 'Sunita Rao', email: 'sunita.rao@gmail.com', phone: '9000000203', city: 'Bangalore' },
  { name: 'Vikram Singh', email: 'vikram.singh@gmail.com', phone: '9000000204', city: 'Delhi' },
  { name: 'Kavya Nair', email: 'kavya.nair@gmail.com', phone: '9000000205', city: 'Kochi' },
  { name: 'Rahul Gupta', email: 'rahul.gupta@gmail.com', phone: '9000000206', city: 'Pune' },
  { name: 'Anjali Desai', email: 'anjali.desai@gmail.com', phone: '9000000207', city: 'Ahmedabad' },
  { name: 'Ravi Krishnan', email: 'ravi.krishnan@gmail.com', phone: '9000000208', city: 'Chennai' },
];

const REVIEW_COMMENTS = [
  'Excellent work! Very professional and clean. Would definitely hire again.',
  'Came on time, did the job perfectly. Very satisfied with the work quality.',
  'Highly skilled and experienced. Finished the work faster than expected.',
  'Great communication throughout the job. Work quality is top-notch.',
  'Very honest and transparent about pricing. No hidden charges at all.',
  'Did a thorough job and even cleaned up after finishing. 5 stars!',
  'Helped me understand the problem and explained the solution clearly.',
  'Best worker I\'ve hired from WorkMitra. Will definitely recommend to friends.',
  'Quick response, arrived on time, and finished the work efficiently.',
  'Professional attitude and excellent craftsmanship. Very impressive.',
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

const randomItem = (arr) => arr[Math.floor(Math.random() * arr.length)];
const randomInt  = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const daysAgo    = (n) => new Date(Date.now() - n * 24 * 60 * 60 * 1000);

// ─── Main seed function ───────────────────────────────────────────────────────

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('\n✅ Connected to MongoDB\n');

    // ── Clear existing seed data ──────────────────────────────────────────────
    console.log('🧹 Clearing previous seed data...');

    // Delete everything — full clean slate
    await Review.deleteMany({});
    await Booking.deleteMany({});
    await WorkerProfile.deleteMany({});
    await Notification.deleteMany({});
    await User.deleteMany({});

    console.log('✅ Cleared\n');

    // ── Create admin ──────────────────────────────────────────────────────────
    console.log('👤 Creating admin account...');
    const admin = await User.create({
      name: 'WorkMitra Admin',
      email: 'admin@workmitra.com',
      password: 'Admin@1234',
      role: 'admin',
      isVerified: true,
    });
    console.log('✅ Admin created: admin@workmitra.com / Admin@1234\n');

    // ── Create customers ──────────────────────────────────────────────────────
    console.log('👥 Creating customers...');
    const customers = [];
    for (const c of CUSTOMER_DATA) {
      const user = await User.create({
        name: c.name,
        email: c.email,
        password: 'Customer@1234',
        phone: c.phone,
        role: 'customer',
        isVerified: true,
        avatar: {
          url: `https://ui-avatars.com/api/?name=${encodeURIComponent(c.name)}&background=6366f1&color=fff&size=200`,
          publicId: '',
        },
      });
      customers.push(user);
      process.stdout.write('.');
    }
    console.log(`\n✅ ${customers.length} customers created\n`);

    // ── Create workers ────────────────────────────────────────────────────────
    console.log('👷 Creating workers and profiles...');
    const workerProfiles = [];

    for (const w of uniqueWorkers) {
      const user = await User.create({
        name: w.name,
        email: w.email,
        password: 'Worker@1234',
        phone: w.phone,
        role: 'worker',
        isVerified: true,
        avatar: { url: w.avatar, publicId: '' },
      });

      const profile = await WorkerProfile.create({
        user: user._id,
        profession: w.profession,
        skills: w.skills,
        experienceYears: w.experienceYears,
        bio: w.bio,
        languages: w.languages,
        rateType: w.rateType,
        rateAmount: w.rateAmount,
        availability: w.availability,
        location: {
          city: w.city,
          state: w.state,
          coordinates: { type: 'Point', coordinates: [0, 0] },
        },
        verification: { status: 'verified' },
        ratingAvg: w.ratingAvg,
        ratingCount: w.ratingCount,
        jobsCompleted: w.jobsCompleted,
        earnings: w.earnings,
        workImages: [],
      });

      workerProfiles.push({ user, profile });
      process.stdout.write('.');
    }
    console.log(`\n✅ ${workerProfiles.length} workers created\n`);

    // ── Create bookings & reviews ─────────────────────────────────────────────
    console.log('📋 Creating bookings and reviews...');
    let bookingCount = 0;
    let reviewCount = 0;

    for (const customer of customers) {
      // Each customer gets 2-4 completed bookings with reviews
      const numBookings = randomInt(2, 4);
      const usedWorkers = new Set();

      for (let i = 0; i < numBookings; i++) {
        // Pick a worker this customer hasn't booked before
        let workerEntry;
        let attempts = 0;
        do {
          workerEntry = randomItem(workerProfiles);
          attempts++;
        } while (usedWorkers.has(workerEntry.profile._id.toString()) && attempts < 20);

        if (usedWorkers.has(workerEntry.profile._id.toString())) continue;
        usedWorkers.add(workerEntry.profile._id.toString());

        const booking = await Booking.create({
          customer: customer._id,
          worker: workerEntry.profile._id,
          date: daysAgo(randomInt(10, 90)),
          timeSlot: randomItem(['9 AM - 12 PM', '10 AM - 1 PM', '2 PM - 5 PM', '11 AM - 2 PM']),
          description: randomItem([
            'Need complete wiring check and repair of faulty switches.',
            'Bathroom tap is leaking, need urgent repair.',
            'Painting 3 rooms, want texture finish on one wall.',
            'AC not cooling, needs gas refill and service.',
            'Need custom wardrobe built for bedroom.',
            'Kitchen tiles are broken, need replacement.',
            'Gate fabrication required for main entrance.',
            'Building boundary wall, need mason for 3 days.',
          ]),
          address: `${randomInt(1, 500)}, Sector ${randomInt(1, 45)}, ${workerEntry.profile.location.city}`,
          status: 'completed',
          totalAmount: workerEntry.profile.rateAmount * randomInt(1, 3),
        });

        bookingCount++;

        // Create a review for this completed booking
        await Review.create({
          booking: booking._id,
          customer: customer._id,
          worker: workerEntry.profile._id,
          rating: randomItem([4, 4, 4, 5, 5, 5, 5]), // bias toward 4-5 stars
          comment: randomItem(REVIEW_COMMENTS),
        });

        reviewCount++;
        process.stdout.write('.');
      }
    }

    console.log(`\n✅ ${bookingCount} bookings created`);
    console.log(`✅ ${reviewCount} reviews created\n`);

    // ── Summary ───────────────────────────────────────────────────────────────
    console.log('═══════════════════════════════════════════');
    console.log('  🎉 WorkMitra seed complete!');
    console.log('═══════════════════════════════════════════');
    console.log(`  👤 Admin:     admin@workmitra.com`);
    console.log(`  🔑 Password:  Admin@1234`);
    console.log(`  👷 Workers:   ${workerProfiles.length} (password: Worker@1234)`);
    console.log(`  👥 Customers: ${customers.length} (password: Customer@1234)`);
    console.log(`  📋 Bookings:  ${bookingCount} (all completed)`);
    console.log(`  ⭐ Reviews:   ${reviewCount}`);
    console.log('═══════════════════════════════════════════');
    console.log('\n  Sample worker logins:');
    console.log('  ramesh.kumar@workmitra.com / Worker@1234');
    console.log('  deepak.chauhan@workmitra.com / Worker@1234');
    console.log('\n  Sample customer logins:');
    console.log('  priya.sharma@gmail.com / Customer@1234');
    console.log('  arjun.mehta@gmail.com / Customer@1234');
    console.log('═══════════════════════════════════════════\n');

  } catch (err) {
    console.error('\n❌ Seed failed:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB\n');
    process.exit(0);
  }
}

seed();
